Project File: 221-3.JOB [Format 3.01 rev.26/3/97]
       JOB_Type: 0 
+  NC_file #1 E:\cursos\CNC\CIFO*San*Feliu*de*Llobregat\Pendrive\Fresadora\221\221-3\221-3.nc 
         Setup: E:\cursos\CNC\CIFO*San*Feliu*de*Llobregat\Pendrive\Fresadora\221\221-3\221-3.stp 
        Stamps: 0 0 0 0 
 
LOG File: 221-3.LOG 
DOC File: 221-3.DOC 
RVP File: 221-3.RVP 
SAV File: .SAV (savEOF:0 savTCHANGE:0 savEVERY:0)
