Project File: Fagor8050.JOB [Format 3.01 rev.26/3/97]
       JOB_Type: 0 
+  NC_file #1 C:\Documents*and*Settings\db2\Escritorio\Plantillas\Fresa\Fagor8050.nc 
         Setup: C:\Documents*and*Settings\db2\Escritorio\Plantillas\Fresa\Fagor8050.stp 
        Stamps: 0 0 0 0 
 
LOG File: Fagor8050.LOG 
DOC File: Fagor8050.DOC 
RVP File: Fagor8050.RVP 
SAV File: .SAV (savEOF:0 savTCHANGE:0 savEVERY:0)
